[package]
name = "beancount-language-server"
version = "1.1.1"
rust-version = "1.59"
edition = "2021"
authors = ["Brian Ryall <polarmutex@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/polarmutex/beancount-language-server"
keywords = ["beancount", "lsp"]
description = """
A language server for the beancount language
"""

[dependencies]
anyhow = "1.0"
bytes = "1.1"
chrono = "0"
clap = "3.1"
dashmap = "5.3"
linked-list = "0.0.3"
log4rs = "1"
log = "0.4"
regex = "1"
ropey = "1.4"
serde = "1.0"
serde_json = "1.0"
shellexpand = "2.0.0"
thiserror = "1.0"
tokio = { version = "1.18", features = ["macros", "rt-multi-thread", "io-std", "io-util", "process", "time"] }
tower-lsp = { version = "0.17.0", features = ["runtime-tokio"] }
tower-test = "0.4.0"
tree-sitter = "0.20"
tree-sitter-beancount = "2.0.0"

[package.metadata.release]
tag = true
